name: build and pull nightly docker image

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: |
          VERSION=$(date +%Y%m%d)-$(git rev-parse --short=6 HEAD)-nightly
          echo ::set-output name=VERSION::${VERSION}
      - name: Write version to webapp
        run: echo "VITE_APP_VERSION=${{ steps.get_version.outputs.VERSION }}" >> webapp/.env.production
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/httpymonitor:nightly"
